/* eslint-disable @typescript-eslint/no-unused-vars */
import { Sora } from 'next/font/google'

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from '@/components/navbar';
import Header from '@/components/header'
import Bio from '@/components/bio';
import Cases from '@/components/selected-projects'
import Articles from '@/components/article';
import Footer from "@/components/footer"
import Services from '@/components/services';


const sora = Sora({ subsets: ['latin'] })


// eslint-disable-next-line @typescript-eslint/no-unused-vars
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Optimización UX :: Consultor UX • Product Designer • Analista CRO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
        <body className={`bg-gray-950 ${sora.className}`}>

        {/* {children} */}
        <Navbar/>
        <Header />
        <Bio />

        <Cases />
        <Articles />
        <Services/>
        <Footer />
      </body>
    </html>
  );
}
